# Install zplug
if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
    source ~/.zplug/init.zsh && zplug update --self
fi
source ~/.zplug/init.zsh

zplug "plugins/git",            from:oh-my-zsh
zplug "plugins/aws",            from:oh-my-zsh
zplug "plugins/fasd",           from:oh-my-zsh
zplug "plugins/jira",           from:oh-my-zsh
zplug "plugins/mvn",            from:oh-my-zsh
zplug "plugins/sbt",            from:oh-my-zsh
zplug "plugins/scala",          from:oh-my-zsh
zplug "plugins/vagrant",        from:oh-my-zsh
zplug "plugins/docker",         from:oh-my-zsh
zplug "plugins/pip",            from:oh-my-zsh
zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh"
zplug "themes/robbyrussell",    from:oh-my-zsh

zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting", defer:3
# load after oh-my-zsh lib to override key bindings (e.g. ^R)
zplug "psprint/history-search-multi-word", defer:2

# Make zplug manage itself
zplug "zplug/zplug", hook-build:"zplug --self-manage"

zplug "djui/alias-tips"

# Needs fzy installed. On Mac Os: brew tap jhawthorn/fzy && brew install fzy
zplug "b4b4r07/enhancd", use:init.sh
export ENHANCD_FILTER=fzy
export ENHANCD_DISABLE_DOT=1 # don't use interactive filter with '..'

zplug "agkozak/zsh-z"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# use Vim as a default editor
export EDITOR='vim'
export VISUAL="vim"

# some installation scripts assume that bash is being used and modify only .bash_profile
[ -f ~/.bash_profile ] && source ~/.bash_profile

# local configuration
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# pull and rebase all repositories you can list within current dir
alias rg-git-pull-rebase-all="ls | xargs -I % sh -xc 'cd % && git diff-index --quiet HEAD -- && git pull --rebase'"

# check if tmux is installed
if `command -v tmux >/dev/null 2>&1`; then
   # Don't use tmux inside emacs (dumb or empty $TERM') or IntelliJ (JetBrains term emulator)
   if [[ $TERM != "dumb" && $TERM != "" && ! $TERM =~ screen && $XDG_CURRENT_DESKTOP != i3 && ! $TERMINAL_EMULATOR =~ JetBrains ]]; then
      exec tmux new-session -A -s main
   fi
fi

if `command -v gpg-agent >/dev/null 2>&1` ; then
    # Since GPG 2.1, gpg-agent auto-starts on demand (https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart)
    # On MacOs it's still v2.0
    GPG_VERSION=`gpg-agent --version 2>&1 >/dev/null | grep gpg-agent | grep -oE '[0-9]+\.[0-9]+'`
    if [ `echo "$GPG_VERSION < 2.1" | bc` -eq 1 ]; then
        # Start gpg-agent or use existing agent. Requires gpg-agent and pinentry-mac.
        if test -f ~/.gnupg/.gpg-agent-info -a -n "$(pgrep gpg-agent)"; then
            source ~/.gnupg/.gpg-agent-info
            export GPG_AGENT_INFO
            GPG_TTY=$(tty)
            export GPG_TTY
        else
            eval $(gpg-agent --daemon --write-env-file ~/.gnupg/.gpg-agent-info)
        fi
    fi
fi

if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

# Source plugins and add commands to $PATH.
# Run at the very end, otherwise tmux will incorrectly resize in terminal on Mac OS
zplug load


# do it after zplug load to get zsh completion for gcloud to work properly
if [ "$(uname)" = "Darwin" ]; then
    GOOGLE_CLOUD_SDK_PATH="$(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk"
    if [ -d $GOOGLE_CLOUD_SDK_PATH ]; then
        export CLOUDSDK_PYTHON="$(brew --prefix)/opt/python@3.8/libexec/bin/python"
        source "$GOOGLE_CLOUD_SDK_PATH/path.zsh.inc"
        source "$GOOGLE_CLOUD_SDK_PATH/completion.zsh.inc"
    fi
fi