# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.synced_folder "../", "/home/vagrant/.dotfiles"

  config.vm.provision :shell, privileged: false, inline: <<-SHELL
    # Change shell to zsh, so that oh-my-zsh doesn't ask for password during installation
    sudo chsh -s /bin/zsh vagrant
    export SHELL=/bin/zsh
    sh .dotfiles/setup.sh
  SHELL
end
