# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.synced_folder "../", "/home/vagrant/.dotfiles"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sh ~/.dotfiles/setup.sh
  SHELL
end
