" Install plugin manager with plugins
if has('nvim')
    source ~/.config/nvim/plug.vim
else
    source ~/.vim/plug.vim
endif

syntax on

set clipboard=unnamedplus

" make cursor a pipe in insert mode and block in normal mode
:let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
